### ISSUE TITLE
Bug: kpt-functions-sdk RUNNER.assertCallback logs expected errors

### ISSUE THREAD

**Issue by karlkfi** [kptdev/kpt#1510]
I expect this to catch the error and validate it:

```
RUNNER.assertCallback(
      undefined,
      undefined,
      FunctionConfigError,
      'Error: Cannot read input. Need either stdin or --input file'
);
```

But even tho the test passes, the jasmine test output still prints the full error message:

```
JASMINE_CONFIG_PATH=jasmine.json jasmine

Error: Cannot read input. Need either stdin or --input file
    at Object.readConfigs (/home/karlisenberg/workspace/blueprints/functions/kpt-set-annotations/node_modules/kpt-functions/dist/src/io.js:61:19)
    at runFn (/home/karlisenberg/workspace/blueprints/functions/kpt-set-annotations/node_modules/kpt-functions/dist/src/run.js:141:32)
    at Object.run (/home/karlisenberg/workspace/blueprints/functions/kpt-set-annotations/node_modules/kpt-functions/dist/src/run.js:71:15)
    at Object.<anonymous> (/home/karlisenberg/workspace/blueprints/functions/kpt-set-annotations/dist/set_annotations.js:34:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)

```

kpt-functions-sdk version: 0.14.5

**Comment by mikebz** [comment]
@mengqiy PTAL

**Comment by CsatariGergely** [comment]
TypeSript SDK is not supported anymore.
