### ISSUE TITLE
e2e tests in cli-utils are flaky

### ISSUE THREAD

**Issue by mortent** [kptdev/kpt#366]
I sometimes see test failures when running the e2e tests from cli-utils locally. Usually the tests will pass if I try again. 

Example output:
```
echo "Error @RunWordpressAndMysql (block #5 in testE2EAgainstLatestRelease) of /Users/me/go/src/sigs.k8s.io/cli-utils/examples/alphaTestExamples/MultipleServcies.md"

kapply apply $BASE/mysql --wait-for-reconcile > $OUTPUT/status;

expectedOutputLine "deployment.apps/mysql is Current: Deployment is available. Replicas: 1"

expectedOutputLine "secret/mysql-pass is Current: Resource is always ready"

expectedOutputLine "configmap/inventory-map-mysql-57005c71 is Current: Resource is always ready"

expectedOutputLine "service/mysql is Current: Service is ready"

kapply apply $BASE/wordpress --wait-for-reconcile > $OUTPUT/status;

expectedOutputLine "configmap/inventory-map-wordpress-2fbd5b91 is Current: Resource is always ready"

expectedOutputLine "service/wordpress is Current: Service is ready"

expectedOutputLine "deployment.apps/wordpress is Current: Deployment is available. Replicas: 1"

----------------------------------------------------------------------

stdOut capture:
----------------------------------------------------------------------

----------------------------------------------------------------------

stdErr capture:
----------------------------------------------------------------------

----------------------------------------------------------------------
F0316 11:34:50.231114   60636 main.go:45] exit status 1
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc0000eba00, 0xc000180000, 0x38, 0x108)
	/Users/me/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0x18c38e0, 0xc000000003, 0xc00013bd50, 0x186e887, 0x7, 0x2d, 0x0)
	/Users/me/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x372
github.com/golang/glog.(*loggingT).printDepth(0x18c38e0, 0x7ffe00000003, 0x1, 0xc000135e48, 0x1, 0x1)
	/Users/me/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:646 +0x129
github.com/golang/glog.(*loggingT).print(...)
	/Users/me/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:637
github.com/golang/glog.Fatal(...)
	/Users/me/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1128
main.trueMain(0xc0000d4040, 0x0, 0x0)
	/Users/me/go/pkg/mod/github.com/monopole/mdrip@v1.0.0/main.go:45 +0x586
main.main()
	/Users/me/go/pkg/mod/github.com/monopole/mdrip@v1.0.0/main.go:70 +0x46
make: *** [test-examples-e2e-kapply] Error 255
```

**Comment by phanimarupaka** [comment]
@mortent Can we close this issue.

**Comment by CsatariGergely** [comment]
We take the Porch version of the tests.
